export default {
    corrective_title: 'Corrective Exercise',
    
    p1: 'Corrective Exercises are techniques used to help you address and fix movement imbalances and their compensations, identify what muscles are weak or strong, lengthened or shortened, and what can be done to correct those imbalances in the body, so that you move better, have less problems and pain, during your exercises or in daily life.  ',
    p2: 'I am certified with the International Sport Sciences Association (ISSA).',
    p3: 'If you have been with recurrent pain during or after exercising, and although you have waited for it to go away, or you have tried to relax the muscle, but you still have it, corrective exercises are for you.',
    p4: 'If you are going to have an operation, and you want to have your body in an optimal state before the operation, then the Corrective Exercises are also for you. In this way you improve the prognosis of post-operative recovery.',
    p5: 'In order to help you correct the imbalance, I use what I learned during the Corrective Exercises certification, plus my knowledge of Applied Kinesiology, Sports Kinesiology developed by John Maguire, Holistic Kinesiology, Koshi Balancing, and Sotai.',
    p6: 'Normally, the muscle that is in pain is not the muscle that needs to be corrected, since this is the muscle that is overworking. You have to find the muscle that is inactive or passive. If you don \'t do this, the pain generated by overarousal will return.',
    
};